services:
  blazorstandalone:
    image: blazorstandalone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
      - 8443:443
    # Volumes are only used for the certificates, so the user can always update it
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
