events { }
   http {
      include mime.types;
      types {
         application/wasm wasm;
       }

    # HTTP
     server {
        listen 80;
        index index.html;

        # Allows for XSS protection
        add_header Content-Security-Policy "
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval';
          style-src 'self' 'unsafe-inline';
          img-src 'self' data:;
          object-src 'none';
          base-uri 'self';
          frame-ancestors 'none';
          form-action 'self';
        " always;


        location / {
           root /var/www/web;
           try_files $uri $uri/ /index.html =404;
        }
     }
    # HTTPS
      server {
        listen 443 ssl;
        # Update this to your actual SNI in the SSL communication, or just comment this line out
        server_name localhost;

        # Replace the file names BUT NOT THE PATH
        ssl_certificate     /etc/nginx/certs/localhost.crt;
        ssl_certificate_key /etc/nginx/certs/localhost.key;

        # SSL defaults for better protection
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        index index.html;

        # Allows for XSS protection
        add_header Content-Security-Policy "
          default-src 'self';
          script-src 'self' 'unsafe-inline' 'unsafe-eval' 'wasm-unsafe-eval';
          style-src 'self' 'unsafe-inline';
          img-src 'self' data:;
          object-src 'none';
          base-uri 'self';
          frame-ancestors 'none';
          form-action 'self';
        " always;


        location / {
            root /var/www/web;
            try_files $uri $uri/ /index.html =404;
        }
      }
}
